-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 20:29:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`server` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `mod-path` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mods` (
  `id` INT NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `steam-id` INT NULL,
  `server_only` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `steam-id_UNIQUE` (`steam-id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mods_mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mods_mapping` (
  `id` INT NOT NULL,
  `foldername` VARCHAR(300) NULL,
  `is_installed` TINYINT NULL,
  `mods_id` INT NOT NULL,
  `server_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mods_folder_mods1_idx` (`mods_id` ASC) VISIBLE,
  INDEX `fk_mods_folder_server1_idx` (`server_id` ASC) VISIBLE,
  CONSTRAINT `fk_mods_folder_mods1`
    FOREIGN KEY (`mods_id`)
    REFERENCES `mydb`.`mods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mods_folder_server1`
    FOREIGN KEY (`server_id`)
    REFERENCES `mydb`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modsets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modsets` (
  `id` INT NOT NULL,
  `name` NVARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mod_mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mod_mapping` (
  `id` INT NOT NULL,
  `modsets_id` INT NOT NULL,
  `mods_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mod_mapping_modsets1_idx` (`modsets_id` ASC) VISIBLE,
  INDEX `fk_mod_mapping_mods1_idx` (`mods_id` ASC) VISIBLE,
  CONSTRAINT `fk_mod_mapping_modsets1`
    FOREIGN KEY (`modsets_id`)
    REFERENCES `mydb`.`modsets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mod_mapping_mods1`
    FOREIGN KEY (`mods_id`)
    REFERENCES `mydb`.`mods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`templates` (
  `id` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  `modsets_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_templates_modsets1_idx` (`modsets_id` ASC) VISIBLE,
  CONSTRAINT `fk_templates_modsets1`
    FOREIGN KEY (`modsets_id`)
    REFERENCES `mydb`.`modsets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
